@startuml
start
fork
:Runs on Ubuntu-latest;
:Checkout Repository;
:Set up Python 3.12;
:Install Dependencies;
:Execute Tests;

if (Tests executed without exceptions) then (yes)
    :Upload Code Coverage report;
else (no)
    stop
endif

fork again
:Runs on Windows-latest;
:Checkout Repository;
:Set up Python 3.12;
:Install Dependencies;
:Execute Tests;

if (Tests executed without exceptions) then (yes)
    :Upload Code Coverage report;
else (no)
    stop
endif

fork again
:Runs on macOS-latest;
:Checkout Repository;
:Set up Python 3.12;
:Install Dependencies;
:Execute Tests;

if (Tests executed without exceptions) then (yes)
    :Upload Code Coverage report;
else (no)
    stop
endif

endfork

:Begin process for setting up Terraform backend;
:Runs on Ubuntu-latest;
:Clone Repository and Execute Terraform Scripts;

:Begin process for setting up ECR Repository;
:Runs on Ubuntu-latest;
:Clone Repository and Execute Terraform Scripts;

if (Approval from reviewers?) then (yes)
    :Begin process for setting up main infrastructure;
    :Runs on Ubuntu-latest;
    :Clone Repository and Execute Terraform Scripts;
    stop
else (no)
    stop

@enduml