@startuml
skinparam linetype polyline
skinparam linetype ortho

package core {
    package constants {
        enum "<<enumeration>>\nHttpMethod" {
            GET
            POST
        }

        enum "<<enumeration>>\nEndpoints" {
            UAT
            PRODUCTION
            MOCK
        }

        enum "<<enumeration>>\nVacancy" {
            AVAILABLE
            FULL
            LIMITED_VACANCY
        }

        enum "<<enumeration>>\nRole" {
            TRAINER
            ASSESSOR
        }

        enum "<<enumeration>>\nModeOfTraining" {
            CLASSROOM
            ASYNCHRONOUS_ELEARNING
            IN_HOUSE
            ON_THE_JOB
            PRACTICAL_PRACTICUM
            SUPERVISED_FIELD
            TRAINEESHIP
            ASSESSMENT
            SYNCHRONOUS_LEARNING
        }

        enum "<<enumeration>>\nIdType" {
            SINGAPORE_BLUE
            SINGAPORE_PINK
            FIN_WORK_PERMIT
            FOREIGN_PASSPORT
            OTHERS
        }

        enum "<<enumeration>>\nSalutations" {
            MR
            MS
            MDM
            MRS
            DR
            PROF
        }

        enum "<<enumeration>>\nMonth" {
            JAN
            FEB
            MAR
            APR
            MAY
            JUN
            JUL
            AUG
            SEP
            OCT
            NOV
            DEC
        }

        enum "<<enumeration>>\nGrade" {
            A
            B
            C
            D
            E
            F
        }

        enum "<<enumeration>>\nResults" {
            PASS
            FAIL
            EXEMPT
        }

        enum "<<enumeration>>\nIdTypeSummary" {
            NRIC
            FIN
            OTHERS
        }

        enum "<<enumeration>>\nAssessmentUpdateVoidActions" {
            UPDATE
            VOID
        }

        enum "<<enumeration>>\nAttendance" {
            CONFIRMED
            UNCONFIRMED
            REJECTED
            TP_VOIDED
        }

        enum "<<enumeration>>\nSortField" {
            UPDATED_ON
            CREATED_ON
            ASSESSMENT_DATE
        }

        enum "<<enumeration>>\nSortOrder" {
            ASCENDING
            DESCENDING
        }

        enum "<<enumeration>>\nSurveyLanguage" {
            ENGLISH
            MANDARIN
            MALAY
            TAMIL
        }

        enum "<<enumeration>>\nCollectionStatus" {
            PENDING_PAYMENT
            PARTIAL_PAYMENT
            FULL_PAYMENT
        }

        enum "<<enumeration>>\nCancellableCollectionStatus" {
            PENDING_PAYMENT
            PARTIAL_PAYMENT
            FULL_PAYMENT
            CANCELLED
        }

        enum "<<enumeration>>\nSponsorshipType" {
            EMPLOYER
            INDIVIDUAL
        }

        enum "<<enumeration>>\nEnrolmentSortField" {
            UPDATED_ON
            CREATED_ON
        }

        enum "<<enumeration>>\nEnrolmentStatus" {
            CONFIRMED
            REJECTED
        }

        enum "<<enumeration>>\nEnrolmentCourseStatus" {
            CONFIRMED
            CANCELLED
        }

        enum OptionalSelector {
            NIL
            YES
            NO
        }
    }
}
@enduml