name: "Remove Secrets from AWS Systems Manager Parameter Store"

on: workflow_dispatch

jobs:
  teardown-dev:
    runs-on: ubuntu-latest
    name: Remove Secrets

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        working-directory: ./SSG-API-Testing-Application-v2/lambda/deploy/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: terraform init
      
      - name: Destroy Main Infrastructure
        working-directory: ./SSG-API-Testing-Application-v2/lambda/deploy/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          TF_VAR_secrets: |
            {
              "/SampleApp/example_secrets/example": {
                "value": "${{ secrets.EXAMPLE }}",
                "description": "An example secret"
              },
              "/SampleApp/example_secrets/another_example": {
                "value": "${{ secrets.ANOTHER_EXAMPLE }}",
                "description": "Another example secret"
              }
            }
        run: terraform destroy -auto-approve